version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    ports:
      - 54411:80
    build:
      context: .
      dockerfile: APIGateway\Dockerfile
        
  encryptionservice:
    image: ${DOCKER_REGISTRY-}encryptionservice
    ports:
      - 54412:80
    build:
      context: .
      dockerfile: EncryptionService\Dockerfile